"""add force_snapshots table

Revision ID: 064bfc3cf7c5
Revises: c862d6bd27bf
Create Date: 2026-08-10 13:42:02.702741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064bfc3cf7c5'
down_revision: Union[str, Sequence[str], None] = 'c862d6bd27bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('force_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('waypoint_type', sa.String(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_force_snapshots_force_id'), 'force_snapshots', ['force_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_force_snapshots_force_id'), table_name='force_snapshots')
    op.drop_table('force_snapshots')
    # ### end Alembic commands ###
