"""special abilities pool and join table

Revision ID: 27b52250a900
Revises: 4bce84c5ebae
Create Date: 2026-07-19 12:55:59.449360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b52250a900'
down_revision: Union[str, Sequence[str], None] = '4bce84c5ebae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_abilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_special_abilities_name'), 'special_abilities', ['name'], unique=True)
    op.create_table('force_special_abilities',
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['special_abilities.id'], ),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('force_id', 'ability_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('force_special_abilities')
    op.drop_index(op.f('ix_special_abilities_name'), table_name='special_abilities')
    op.drop_table('special_abilities')
    # ### end Alembic commands ###
