"""core force schema

Revision ID: 4bce84c5ebae
Revises: e3c21f33f8fc
Create Date: 2026-07-19 12:44:56.055661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bce84c5ebae'
down_revision: Union[str, Sequence[str], None] = 'e3c21f33f8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('starting_warchest', sa.Integer(), nullable=False),
    sa.Column('current_warchest', sa.Integer(), nullable=False),
    sa.Column('wp_multiplier', sa.Integer(), nullable=False),
    sa.Column('current_date', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('special_abilities', sa.JSON(), nullable=False),
    sa.Column('other_actions_log', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elementals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('commander', sa.String(), nullable=False),
    sa.Column('gunnery', sa.Integer(), nullable=False),
    sa.Column('antimech', sa.Integer(), nullable=False),
    sa.Column('suits_destroyed', sa.Integer(), nullable=False),
    sa.Column('suits_damaged', sa.Integer(), nullable=False),
    sa.Column('bv', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('warchest_cost', sa.Integer(), nullable=False),
    sa.Column('activity_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elementals_force_id'), 'elementals', ['force_id'], unique=False)
    op.create_table('full_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('force_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_full_snapshots_force_id'), 'full_snapshots', ['force_id'], unique=False)
    op.create_table('mechs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('bv', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('warchest_cost', sa.Integer(), nullable=False),
    sa.Column('activity_log', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechs_force_id'), 'mechs', ['force_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=False),
    sa.Column('recap', sa.Text(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('assigned_mechs', sa.JSON(), nullable=False),
    sa.Column('assigned_elementals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('in_game_date', sa.String(), nullable=False),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('sp_budget', sa.Integer(), nullable=True),
    sa.Column('sp_purchases', sa.JSON(), nullable=False),
    sa.Column('total_tonnage', sa.Integer(), nullable=True),
    sa.Column('op_for_units', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_force_id'), 'missions', ['force_id'], unique=False)
    op.create_table('pilots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gunnery', sa.Integer(), nullable=False),
    sa.Column('piloting', sa.Integer(), nullable=False),
    sa.Column('injuries', sa.Integer(), nullable=False),
    sa.Column('dezgra', sa.Boolean(), nullable=False),
    sa.Column('history', sa.Text(), nullable=False),
    sa.Column('warchest_cost', sa.Integer(), nullable=False),
    sa.Column('activity_log', sa.JSON(), nullable=False),
    sa.Column('combat_record', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilots_force_id'), 'pilots', ['force_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('force_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('current_warchest', sa.Integer(), nullable=False),
    sa.Column('starting_warchest', sa.Integer(), nullable=False),
    sa.Column('net_warchest_change', sa.Integer(), nullable=False),
    sa.Column('missions_completed', sa.Integer(), nullable=False),
    sa.Column('units', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['force_id'], ['forces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_force_id'), 'snapshots', ['force_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshots_force_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_pilots_force_id'), table_name='pilots')
    op.drop_table('pilots')
    op.drop_index(op.f('ix_missions_force_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_mechs_force_id'), table_name='mechs')
    op.drop_table('mechs')
    op.drop_index(op.f('ix_full_snapshots_force_id'), table_name='full_snapshots')
    op.drop_table('full_snapshots')
    op.drop_index(op.f('ix_elementals_force_id'), table_name='elementals')
    op.drop_table('elementals')
    op.drop_table('forces')
    # ### end Alembic commands ###
