"""add image binary columns to forces mechs elementals

Revision ID: 5b7ca80172e3
Revises: 064bfc3cf7c5
Create Date: 2026-08-11 02:51:53.067921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7ca80172e3'
down_revision: Union[str, Sequence[str], None] = '064bfc3cf7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elementals', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('elementals', sa.Column('image_mime_type', sa.String(), nullable=True))
    op.add_column('forces', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('forces', sa.Column('image_mime_type', sa.String(), nullable=True))
    op.add_column('mechs', sa.Column('image_data', sa.LargeBinary(), nullable=True))
    op.add_column('mechs', sa.Column('image_mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mechs', 'image_mime_type')
    op.drop_column('mechs', 'image_data')
    op.drop_column('forces', 'image_mime_type')
    op.drop_column('forces', 'image_data')
    op.drop_column('elementals', 'image_mime_type')
    op.drop_column('elementals', 'image_data')
    # ### end Alembic commands ###
