"""pilot special abilities pool

Revision ID: 81c5b91ac451
Revises: a28c833e7254
Create Date: 2026-07-19 14:43:57.714147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c5b91ac451'
down_revision: Union[str, Sequence[str], None] = 'a28c833e7254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_special_abilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_special_abilities_name'), 'pilot_special_abilities', ['name'], unique=True)
    op.create_table('pilot_spa_assignments',
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('spa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.ForeignKeyConstraint(['spa_id'], ['pilot_special_abilities.id'], ),
    sa.PrimaryKeyConstraint('pilot_id', 'spa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_spa_assignments')
    op.drop_index(op.f('ix_pilot_special_abilities_name'), table_name='pilot_special_abilities')
    op.drop_table('pilot_special_abilities')
    # ### end Alembic commands ###
