"""achievements and sp purchases reference pools

Revision ID: a28c833e7254
Revises: 27b52250a900
Create Date: 2026-07-19 13:55:51.609055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28c833e7254'
down_revision: Union[str, Sequence[str], None] = '27b52250a900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sp_choices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_sp_purchases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.String(), nullable=False),
    sa.Column('choice_id', sa.String(), nullable=True),
    sa.Column('cost_at_purchase', sa.Float(), nullable=False),
    sa.Column('name_at_purchase', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['sp_choices.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_sp_purchases_mission_id'), 'mission_sp_purchases', ['mission_id'], unique=False)
    op.create_table('pilot_achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(), nullable=False),
    sa.Column('earned_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement_definitions.id'], ),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pilot_achievements_pilot_id'), 'pilot_achievements', ['pilot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pilot_achievements_pilot_id'), table_name='pilot_achievements')
    op.drop_table('pilot_achievements')
    op.drop_index(op.f('ix_mission_sp_purchases_mission_id'), table_name='mission_sp_purchases')
    op.drop_table('mission_sp_purchases')
    op.drop_table('sp_choices')
    op.drop_table('achievement_definitions')
    # ### end Alembic commands ###
