"""mech catalog table

Revision ID: be34ee216040
Revises: 81c5b91ac451
Create Date: 2026-07-19 15:24:42.340407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be34ee216040'
down_revision: Union[str, Sequence[str], None] = '81c5b91ac451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mech_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mul_id', sa.Integer(), nullable=True),
    sa.Column('chassis', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('bv', sa.Integer(), nullable=False),
    sa.Column('tonnage', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('techbase', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mech_catalog_chassis'), 'mech_catalog', ['chassis'], unique=False)
    op.create_index(op.f('ix_mech_catalog_mul_id'), 'mech_catalog', ['mul_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mech_catalog_mul_id'), table_name='mech_catalog')
    op.drop_index(op.f('ix_mech_catalog_chassis'), table_name='mech_catalog')
    op.drop_table('mech_catalog')
    # ### end Alembic commands ###
