"""add force starting_date

Revision ID: c862d6bd27bf
Revises: d6f3e50ef277
Create Date: 2026-08-10 12:40:44.951514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c862d6bd27bf'
down_revision: Union[str, Sequence[str], None] = 'd6f3e50ef277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'forces',
        sa.Column('starting_date', sa.String(), nullable=False, server_default='3025-01-01'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forces', 'starting_date')
    # ### end Alembic commands ###
