"""mech catalog rich fields

Revision ID: f666a8ff05f2
Revises: be34ee216040
Create Date: 2026-07-19 17:46:49.710922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f666a8ff05f2'
down_revision: Union[str, Sequence[str], None] = 'be34ee216040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mech_catalog', sa.Column('walk', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('max_walk', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('jump', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('max_jump', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('heat', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('dissipation', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('dissipation_efficiency', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('mech_catalog', sa.Column('components', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mech_catalog', 'components')
    op.drop_column('mech_catalog', 'dissipation_efficiency')
    op.drop_column('mech_catalog', 'dissipation')
    op.drop_column('mech_catalog', 'heat')
    op.drop_column('mech_catalog', 'max_jump')
    op.drop_column('mech_catalog', 'jump')
    op.drop_column('mech_catalog', 'max_walk')
    op.drop_column('mech_catalog', 'walk')
    # ### end Alembic commands ###
